package db

import "time"

// TaskStatus represents the lifecycle state of a task.
type TaskStatus string

const (
	TaskStatusCreated   TaskStatus = "created"
	TaskStatusPlanning  TaskStatus = "planning"
	TaskStatusPlanned   TaskStatus = "planned"
	TaskStatusApproved  TaskStatus = "approved"
	TaskStatusRunning   TaskStatus = "running"
	TaskStatusPaused    TaskStatus = "paused"
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusFailed    TaskStatus = "failed"
	TaskStatusCancelled TaskStatus = "cancelled"
)

// Task represents a unit of work submitted to Klaudio.
type Task struct {
	ID           string     `json:"id"`
	Name         string     `json:"name"`
	Prompt       string     `json:"prompt"`
	Status       TaskStatus `json:"status"`
	RepoConfig   *string    `json:"repo_config,omitempty"`   // JSON string
	TeamTemplate *string    `json:"team_template,omitempty"`
	OutputFiles  *string    `json:"output_files,omitempty"`  // JSON array string
	Error        *string    `json:"error,omitempty"`
	HasState     bool       `json:"has_state"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	StartedAt    *time.Time `json:"started_at,omitempty"`
	PausedAt     *time.Time `json:"paused_at,omitempty"`
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
}

// Plan represents an execution plan generated by the planner agent.
type Plan struct {
	ID              string    `json:"id"`
	TaskID          string    `json:"task_id"`
	Analysis        *string   `json:"analysis,omitempty"`
	Strategy        string    `json:"strategy"`
	Subtasks        string    `json:"subtasks"` // JSON array
	EstimatedAgents int       `json:"estimated_agents"`
	Notes           *string   `json:"notes,omitempty"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

// Subtask is a single unit within an execution plan (stored as JSON inside Plan.Subtasks).
type Subtask struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	Description   string   `json:"description"`
	Prompt        string   `json:"prompt"`
	DependsOn     []string `json:"depends_on"`
	FilesInvolved []string `json:"files_involved"`
	Complexity    string   `json:"complexity"`
	AgentRole     string   `json:"agent_role"`
	Status        string   `json:"status"`
	AgentID       string   `json:"agent_id,omitempty"`
}

// Agent represents a Claude Code instance running in a Docker container.
type Agent struct {
	ID          string     `json:"id"`
	TaskID      string     `json:"task_id"`
	SubtaskID   *string    `json:"subtask_id,omitempty"`
	ContainerID *string    `json:"container_id,omitempty"`
	Role        string     `json:"role"`
	Status      string     `json:"status"`
	ExitCode    *int       `json:"exit_code,omitempty"`
	Error       *string    `json:"error,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	StartedAt   *time.Time `json:"started_at,omitempty"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`
}

// Event records a state change or notable occurrence for a task.
type Event struct {
	ID        int64     `json:"id"`
	TaskID    string    `json:"task_id"`
	AgentID   *string   `json:"agent_id,omitempty"`
	Type      string    `json:"type"`
	Data      *string   `json:"data,omitempty"` // JSON payload
	CreatedAt time.Time `json:"created_at"`
}

// TaskFile represents a file uploaded to or produced by a task.
type TaskFile struct {
	ID        string    `json:"id"`
	TaskID    string    `json:"task_id"`
	Name      string    `json:"name"`
	Direction string    `json:"direction"` // "input" | "output"
	Path      string    `json:"path"`
	Size      *int64    `json:"size,omitempty"`
	MimeType  *string   `json:"mime_type,omitempty"`
	CreatedAt time.Time `json:"created_at"`
}

// RepoTemplate is a saved repository configuration that can be reused across tasks.
type RepoTemplate struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	URL           string    `json:"url"`
	DefaultBranch string    `json:"default_branch"`
	AccessToken   *string   `json:"access_token,omitempty"`
	AutoBranch    bool      `json:"auto_branch"`
	AutoCommit    bool      `json:"auto_commit"`
	AutoPush      bool      `json:"auto_push"`
	AutoPR        bool      `json:"auto_pr"`
	PRTarget      string    `json:"pr_target"`
	PRReviewers   *string   `json:"pr_reviewers,omitempty"` // JSON array
	EnableMemory  bool      `json:"enable_memory"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// RepoMemory holds a cached codebase analysis for a repo template at a specific commit.
type RepoMemory struct {
	ID             string    `json:"id"`
	RepoTemplateID string    `json:"repo_template_id"`
	Branch         string    `json:"branch"`
	CommitHash     string    `json:"commit_hash"`
	Content        string    `json:"content"`               // Markdown summary
	FileTree       *string   `json:"file_tree,omitempty"`   // JSON
	Languages      *string   `json:"languages,omitempty"`   // JSON
	Frameworks     *string   `json:"frameworks,omitempty"`  // JSON
	KeyFiles       *string   `json:"key_files,omitempty"`   // JSON
	Dependencies   *string   `json:"dependencies,omitempty"`// JSON
	CreatedAt      time.Time `json:"created_at"`
}

// Checkpoint captures the full state of a task at a point in time for resume.
type Checkpoint struct {
	ID           string    `json:"id"`
	TaskID       string    `json:"task_id"`
	StateDir     string    `json:"state_dir"`
	PlanProgress string    `json:"plan_progress"` // JSON
	AgentStates  *string   `json:"agent_states,omitempty"` // JSON
	RepoState    *string   `json:"repo_state,omitempty"`   // JSON
	ResumePrompt *string   `json:"resume_prompt,omitempty"`
	SizeBytes    *int64    `json:"size_bytes,omitempty"`
	CreatedAt    time.Time `json:"created_at"`
}

// PlanProgress tracks which subtasks in a plan have been completed (stored as JSON in Checkpoint).
type PlanProgress struct {
	PlanID            string   `json:"plan_id"`
	CompletedSubtasks []string `json:"completed_subtasks"`
	CurrentSubtask    string   `json:"current_subtask"`
	FailedSubtasks    []string `json:"failed_subtasks"`
}

// AgentState captures per-agent state at checkpoint time (stored as JSON in Checkpoint).
type AgentState struct {
	AgentID    string `json:"agent_id"`
	SubtaskID  string `json:"subtask_id"`
	Status     string `json:"status"`
	LastOutput string `json:"last_output"`
}

// RepoState captures repository state at checkpoint time (stored as JSON in Checkpoint).
type RepoState struct {
	Branch           string   `json:"branch"`
	LastCommitHash   string   `json:"last_commit_hash"`
	UncommittedFiles []string `json:"uncommitted_files"`
}

// PlannerQuestion represents a clarification question from the planner agent.
type PlannerQuestion struct {
	ID          string     `json:"id"`
	TaskID      string     `json:"task_id"`
	Text        string     `json:"text"`
	Answer      *string    `json:"answer,omitempty"`
	Status      string     `json:"status"` // "pending" | "answered"
	Suggestions *string    `json:"suggestions,omitempty"` // JSON array of suggestion strings
	Options     *string    `json:"options,omitempty"`     // JSON array of option strings
	AskedAt     time.Time  `json:"asked_at"`
	AnsweredAt  *time.Time `json:"answered_at,omitempty"`
}

// TeamTemplate is a reusable team configuration that guides the planner.
type TeamTemplate struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	MaxAgents   int       `json:"max_agents"`
	Review      bool      `json:"review"`
	Roles       string    `json:"roles"` // JSON array of TeamRole
	Mode        string    `json:"mode"`  // "sequential" (default) or "collaborative"
	IsDefault   bool      `json:"is_default"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// TeamRole defines a role within a team template (stored as JSON in TeamTemplate.Roles).
type TeamRole struct {
	Name         string `json:"name"`
	Description  string `json:"description"`
	PromptHint   string `json:"prompt_hint"`
	MaxInstances int    `json:"max_instances"`
	RunLast      bool   `json:"run_last"`
}

// AgentMessage represents a message exchanged between agents during execution.
type AgentMessage struct {
	ID            int64     `json:"id"`
	TaskID        string    `json:"task_id"`
	FromAgentID   *string   `json:"from_agent_id,omitempty"`
	FromSubtaskID *string   `json:"from_subtask_id,omitempty"`
	ToAgentID     *string   `json:"to_agent_id,omitempty"`
	ToSubtaskID   *string   `json:"to_subtask_id,omitempty"`
	MsgType       string    `json:"msg_type"` // "message", "context", "summary"
	Content       string    `json:"content"`
	CreatedAt     time.Time `json:"created_at"`
}

// RepoConfig holds repository configuration for a task (stored as JSON in Task.RepoConfig).
type RepoConfig struct {
	URL            string   `json:"url"`
	Branch         string   `json:"branch"`
	AccessToken    string   `json:"access_token"`
	AutoBranch     bool     `json:"auto_branch"`
	AutoCommit     bool     `json:"auto_commit"`
	AutoPush       bool     `json:"auto_push"`
	AutoPR         bool     `json:"auto_pr"`
	PRTarget       string   `json:"pr_target"`
	PRReviewers    []string `json:"pr_reviewers,omitempty"`
	RepoTemplateID string   `json:"repo_template_id,omitempty"`
	EnableMemory   bool     `json:"enable_memory,omitempty"`
}
